export type ExposureMode = "revenue" | "opIncome";
export type Risk = "low" | "medium" | "high";
export type Category = "silicon" | "physical infra" | "power" | "cloud" | "apps" | "other";
export type Confidence = "reported" | "derived" | "proxy" | "speculative";

export type Layer = {
  id: string;
  order: number;
  name: string;
  subtitle: string;
  category: Category;
  method: string;
};

export type Source = {
  id: string;
  name: string;
  publisher: string;
  url: string;
};

export type Company = {
  id: string;
  name: string;
  ticker?: string;
  layerId: string;
  category: Category;
  layerShare: number;
  aiRevenueMix: number;
  aiOpIncomeMix: number;
  coverageAt15Gw: number;
  capacityGw?: number;
  substitutionRisk: Risk;
  confidence: Confidence;
  sourceIds: string[];
  sourceNote: string;
  thesis: string;
  audit: string;
  valuationLens: string;
};

export const lastUpdated = "May 4, 2026";

export const layers: Layer[] = [
  {
    id: "commodities",
    order: 1,
    name: "Commodities",
    subtitle: "cement / steel / copper",
    category: "physical infra",
    method: "AI mix is a proxy for data-center construction exposure, not direct AI revenue disclosure.",
  },
  {
    id: "construction",
    order: 2,
    name: "Construction / EPC",
    subtitle: "site work / electrical",
    category: "physical infra",
    method: "Layer share uses public-company scale and data-center/electrical exposure proxies.",
  },
  {
    id: "generation",
    order: 3,
    name: "Power Generation",
    subtitle: "gas turbines / fuel cells",
    category: "power",
    method: "Coverage is derived from disclosed backlog/slot GW where available; AI share remains a proxy.",
  },
  {
    id: "ipps",
    order: 4,
    name: "Power IPPs",
    subtitle: "PPA providers",
    category: "power",
    method: "Coverage is based on disclosed or reported data-center power commitments and merchant generation optionality.",
  },
  {
    id: "grid",
    order: 5,
    name: "Grid / Transformers / Switchgear",
    subtitle: "electrical equipment",
    category: "power",
    method: "AI mix uses disclosed data-center momentum in electrical orders/backlog where available.",
  },
  {
    id: "cooling",
    order: 6,
    name: "Cooling",
    subtitle: "liquid cooling / thermal / UPS",
    category: "physical infra",
    method: "AI mix reflects data-center order exposure and liquid-cooling relevance.",
  },
  {
    id: "lithography",
    order: 7,
    name: "Lithography / Fab Equipment",
    subtitle: "wafer fab tools",
    category: "silicon",
    method: "AI mix is derived from leading-edge logic/memory exposure; most equipment vendors do not disclose AI revenue.",
  },
  {
    id: "foundry",
    order: 8,
    name: "Foundry",
    subtitle: "leading-edge wafers",
    category: "silicon",
    method: "AI mix uses HPC/advanced-node demand as a proxy for AI silicon exposure.",
  },
  {
    id: "memory",
    order: 9,
    name: "HBM Memory",
    subtitle: "high-bandwidth memory",
    category: "silicon",
    method: "AI mix is derived from HBM/data-center memory disclosures and product mix.",
  },
  {
    id: "packaging",
    order: 10,
    name: "Advanced Packaging",
    subtitle: "CoWoS / 2.5D / 3D",
    category: "silicon",
    method: "AI mix is proxied from advanced packaging demand tied to accelerators and HBM.",
  },
  {
    id: "accelerators",
    order: 11,
    name: "AI Accelerators",
    subtitle: "GPUs / ASICs",
    category: "silicon",
    method: "AI mix is derived from disclosed data-center or AI semiconductor revenue.",
  },
  {
    id: "optics",
    order: 12,
    name: "Optical Interconnect & Networking",
    subtitle: "switching / transceivers / AECs",
    category: "silicon",
    method: "AI mix uses cloud/AI networking and datacom disclosures where available.",
  },
  {
    id: "systems",
    order: 13,
    name: "System Integration / Racks / EMS",
    subtitle: "racks / AI factories",
    category: "physical infra",
    method: "AI mix is based on server, rack, and AI infrastructure backlog disclosures or proxies.",
  },
  {
    id: "hyperscalers",
    order: 14,
    name: "Hyperscalers",
    subtitle: "diversified clouds",
    category: "cloud",
    method: "AI mix is derived from AI run-rate, Azure AI disclosures, OCI RPO, and cloud growth.",
  },
  {
    id: "neoclouds",
    order: 15,
    name: "Neoclouds",
    subtitle: "pure-play AI clouds",
    category: "cloud",
    method: "Coverage uses contracted power where available; revenue mix is near pure-play AI infrastructure.",
  },
];

export const sources: Source[] = [
  {
    id: "nvda-fy26",
    name: "NVIDIA Announces Financial Results for Fourth Quarter and Fiscal 2026",
    publisher: "NVIDIA Investor Relations",
    url: "https://investor.nvidia.com/news/press-release-details/2026/NVIDIA-Announces-Financial-Results-for-Fourth-Quarter-and-Fiscal-2026/",
  },
  {
    id: "amd-fy25",
    name: "AMD Reports Fourth Quarter and Full Year 2025 Financial Results",
    publisher: "AMD Investor Relations",
    url: "https://ir.amd.com/news-events/press-releases/detail/1276/amd-reports-fourth-quarter-and-full-year-2025-financial-results",
  },
  {
    id: "broadcom-fy25",
    name: "Broadcom Announces Fourth Quarter and Fiscal Year 2025 Financial Results",
    publisher: "Broadcom Investor Relations",
    url: "https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-fourth-quarter-and-fiscal-year-2025",
  },
  {
    id: "tsmc-2025",
    name: "TSMC 2025 Annual Report",
    publisher: "TSMC Investor Relations",
    url: "https://investor.tsmc.com/static/annualReports/2025/english/index.html",
  },
  {
    id: "asml-2025",
    name: "ASML 2025 Annual Report",
    publisher: "ASML",
    url: "https://www.asml.com/en/investors/annual-report/2025",
  },
  {
    id: "asml-q425",
    name: "ASML reports 2025 fourth-quarter and full-year results",
    publisher: "ASML",
    url: "https://www.asml.com/en/news/press-releases/2026/q4-2025-financial-results",
  },
  {
    id: "skhynix-fy25",
    name: "SK hynix Announces FY25 Financial Results",
    publisher: "SK hynix Newsroom",
    url: "https://news.skhynix.com/sk-hynix-announces-fy25-financial-results/",
  },
  {
    id: "micron-q225",
    name: "Micron Reports Results for the Second Quarter of Fiscal 2025",
    publisher: "Micron Investor Relations",
    url: "https://investors.micron.com/news-releases/news-release-details/micron-technology-inc-reports-results-second-quarter-fiscal-2025",
  },
  {
    id: "arista-fy25",
    name: "Arista Reports Fourth Quarter and Year End 2025 Financial Results",
    publisher: "Arista",
    url: "https://www.arista.com/en/company/news/press-release/23416-pr-20260212",
  },
  {
    id: "fabrinet-fy25",
    name: "Fabrinet Announces Fourth Quarter and Fiscal Year 2025 Financial Results",
    publisher: "Fabrinet Investor Relations",
    url: "https://investor.fabrinet.com/news-releases/news-release-details/fabrinet-announces-fourth-quarter-and-fiscal-year-2025-financial",
  },
  {
    id: "eaton-q425",
    name: "Eaton Reports Record Fourth Quarter 2025 Results",
    publisher: "Eaton",
    url: "https://www.eaton.com/us/en-us/company/news-insights/news-releases/2026/eaton-reports-record-fourth-quarter-2025-results.html",
  },
  {
    id: "gevernova-fy25",
    name: "GE Vernova Reports Fourth Quarter and Full Year 2025 Results",
    publisher: "GE Vernova",
    url: "https://www.gevernova.com/news/press-releases/ge-vernova-reports-fourth-quarter-full-year-2025-financial-results",
  },
  {
    id: "coreweave-q425",
    name: "CoreWeave Reports Strong Fourth Quarter and Fiscal Year 2025 Results",
    publisher: "Nasdaq / CoreWeave press release",
    url: "https://www.nasdaq.com/press-release/coreweave-reports-strong-fourth-quarter-and-fiscal-year-2025-results-2026-02-26",
  },
  {
    id: "coreweave-q225",
    name: "CoreWeave Reports Strong Second Quarter 2025 Results",
    publisher: "CoreWeave Investor Relations",
    url: "https://investors.coreweave.com/news/news-details/2025/CoreWeave-Reports-Strong-Second-Quarter-2025-Results/default.aspx",
  },
  {
    id: "oracle-q3fy26",
    name: "Oracle Announces Fiscal Year 2026 Third Quarter Financial Results",
    publisher: "Oracle Investor Relations",
    url: "https://investor.oracle.com/investor-news/news-details/2026/Oracle-Announces-Fiscal-Year-2026-Third-Quarter-Financial-Results/default.aspx",
  },
  {
    id: "microsoft-q3fy26",
    name: "Microsoft Cloud and AI Strength Fuels Third Quarter Results",
    publisher: "Microsoft Investor Relations",
    url: "https://www.microsoft.com/en-us/investor/earnings/fy-2026-q3/press-release-webcast",
  },
  {
    id: "microsoft-cloud-q3fy26",
    name: "FY26 Q3 Intelligent Cloud Performance",
    publisher: "Microsoft Investor Relations",
    url: "https://www.microsoft.com/en-us/Investor/earnings/FY-2026-Q3/intelligent-cloud-performance",
  },
  {
    id: "amazon-q126",
    name: "CEO Andy Jassy on why customers are choosing AWS for AI",
    publisher: "Amazon",
    url: "https://www.aboutamazon.com/news/company-news/amazon-ceo-andy-jassy-aws-ai-q1-2026-earnings",
  },
  {
    id: "snowflake-fy26",
    name: "Snowflake Reports Fourth Quarter and Full-Year Fiscal 2026 Results",
    publisher: "Snowflake",
    url: "https://www.snowflake.com/en/news/press-releases/snowflake-reports-financial-results-for-the-fourth-quarter-and-full-year-of-fiscal-2026/",
  },
  {
    id: "servicenow-q126",
    name: "ServiceNow Reports First Quarter 2026 Financial Results",
    publisher: "ServiceNow Investor Relations",
    url: "https://investor.servicenow.com/news/news-details/2026/ServiceNow-Reports-First-Quarter-2026-Financial-Results/default.aspx",
  },
];

export const companies: Company[] = [
  {
    id: "fcx",
    name: "Freeport-McMoRan",
    ticker: "FCX",
    layerId: "commodities",
    category: "physical infra",
    layerShare: 20,
    aiRevenueMix: 6,
    aiOpIncomeMix: 7,
    coverageAt15Gw: 120,
    substitutionRisk: "low",
    confidence: "speculative",
    sourceIds: [],
    sourceNote: "Proxy: copper demand is broad-market and not disclosed as AI/data-center revenue.",
    thesis: "A copper beta rather than an AI pure play. Useful as upstream bottleneck exposure, but very diluted.",
    audit: "Keep as a low-confidence commodity proxy until a sourced data-center copper intensity model is added.",
    valuationLens: "AI can tighten copper demand, but company-level AI beta is small versus macro commodity drivers.",
  },
  {
    id: "clfs",
    name: "Cleveland-Cliffs",
    ticker: "CLF",
    layerId: "commodities",
    category: "physical infra",
    layerShare: 12,
    aiRevenueMix: 3,
    aiOpIncomeMix: 5,
    coverageAt15Gw: 250,
    substitutionRisk: "low",
    confidence: "speculative",
    sourceIds: [],
    sourceNote: "Proxy: steel/electrical steel has broad end-market exposure; AI share is not disclosed.",
    thesis: "Capacity screen reads saturated because the relevant output sells into many markets, not only data centers.",
    audit: "Needs a transformer/GOES-specific revenue bridge before this belongs in a high-conviction basket.",
    valuationLens: "More commodity cyclicality than AI beta.",
  },
  {
    id: "pwr",
    name: "Quanta Services",
    ticker: "PWR",
    layerId: "construction",
    category: "physical infra",
    layerShare: 28,
    aiRevenueMix: 18,
    aiOpIncomeMix: 20,
    coverageAt15Gw: 70,
    substitutionRisk: "medium",
    confidence: "proxy",
    sourceIds: [],
    sourceNote: "Proxy based on grid/electrical construction exposure; no clean AI revenue disclosure found in this pass.",
    thesis: "High-quality electrical construction exposure with AI data centers as one demand driver among several.",
    audit: "Needs backlog by customer/end-market to raise confidence.",
    valuationLens: "Infrastructure compounder, not a direct AI revenue story.",
  },
  {
    id: "eme",
    name: "EMCOR",
    ticker: "EME",
    layerId: "construction",
    category: "physical infra",
    layerShare: 18,
    aiRevenueMix: 14,
    aiOpIncomeMix: 15,
    coverageAt15Gw: 55,
    substitutionRisk: "medium",
    confidence: "proxy",
    sourceIds: [],
    sourceNote: "Proxy based on mechanical/electrical services exposure to data-center construction.",
    thesis: "Data-center construction can pull revenue forward, but the company is not an AI pure play.",
    audit: "Add segment backlog by vertical if disclosed.",
    valuationLens: "Execution quality and backlog conversion matter more than AI narrative.",
  },
  {
    id: "gev",
    name: "GE Vernova",
    ticker: "GEV",
    layerId: "generation",
    category: "power",
    layerShare: 34,
    aiRevenueMix: 18,
    aiOpIncomeMix: 22,
    coverageAt15Gw: 185,
    capacityGw: 27.4,
    substitutionRisk: "low",
    confidence: "derived",
    sourceIds: ["gevernova-fy25"],
    sourceNote: "GE Vernova disclosed gas equipment backlog and slot reservations grew to 83 GW; AI/data-center share is estimated, not reported.",
    thesis: "Gas turbine scarcity is an AI power bottleneck, but the backlog serves utility and industrial demand too.",
    audit: "Coverage uses one-third of 83 GW as data-center-related proxy. Confidence should improve with customer mix disclosure.",
    valuationLens: "A power supercycle stock with AI as a strong incremental demand source.",
  },
  {
    id: "be",
    name: "Bloom Energy",
    ticker: "BE",
    layerId: "generation",
    category: "power",
    layerShare: 7,
    aiRevenueMix: 35,
    aiOpIncomeMix: 35,
    coverageAt15Gw: 40,
    substitutionRisk: "medium",
    confidence: "proxy",
    sourceIds: [],
    sourceNote: "Proxy: fuel cells can serve data-center behind-the-meter power, but AI revenue mix is not consistently disclosed.",
    thesis: "Potentially high beta if behind-the-meter power becomes a standard data-center pattern.",
    audit: "Needs contracted MW and data-center customer backlog.",
    valuationLens: "Higher upside and higher technology/execution risk than turbine incumbents.",
  },
  {
    id: "ceg",
    name: "Constellation Energy",
    ticker: "CEG",
    layerId: "ipps",
    category: "power",
    layerShare: 35,
    aiRevenueMix: 8,
    aiOpIncomeMix: 11,
    coverageAt15Gw: 55,
    substitutionRisk: "low",
    confidence: "proxy",
    sourceIds: [],
    sourceNote: "Proxy: nuclear/IPP exposure to data-center PPAs; company-level AI revenue is not disclosed.",
    thesis: "Scarce clean firm power makes the asset base strategically relevant even when AI revenue mix is modest.",
    audit: "Add PPA-level MW and pricing detail where available.",
    valuationLens: "Power scarcity and contract repricing are the real variables.",
  },
  {
    id: "tln",
    name: "Talen Energy",
    ticker: "TLN",
    layerId: "ipps",
    category: "power",
    layerShare: 10,
    aiRevenueMix: 45,
    aiOpIncomeMix: 50,
    coverageAt15Gw: 60,
    substitutionRisk: "low",
    confidence: "proxy",
    sourceIds: [],
    sourceNote: "Proxy: data-center-linked power arrangements make the AI beta materially higher than diversified IPPs.",
    thesis: "More direct data-center power optionality than most IPPs, but contract/regulatory details drive outcomes.",
    audit: "Needs explicit contracted MW and counterparty economics.",
    valuationLens: "Potentially high beta to colocated power, with regulatory/political risk.",
  },
  {
    id: "etn",
    name: "Eaton",
    ticker: "ETN",
    layerId: "grid",
    category: "power",
    layerShare: 18,
    aiRevenueMix: 18,
    aiOpIncomeMix: 22,
    coverageAt15Gw: 65,
    substitutionRisk: "low",
    confidence: "derived",
    sourceIds: ["eaton-q425"],
    sourceNote: "Eaton disclosed Electrical Americas order acceleration driven by data-center momentum and Electrical sector backlog growth.",
    thesis: "A cleaner public-market proxy for electrical bottlenecks than many construction or commodity names.",
    audit: "AI mix is derived from data-center order commentary plus Electrical Americas scale; not directly reported.",
    valuationLens: "High-quality compounder with data-center demand supporting backlog and margins.",
  },
  {
    id: "schneider",
    name: "Schneider Electric",
    layerId: "grid",
    category: "power",
    layerShare: 18,
    aiRevenueMix: 22,
    aiOpIncomeMix: 23,
    coverageAt15Gw: 70,
    substitutionRisk: "low",
    confidence: "proxy",
    sourceIds: [],
    sourceNote: "Proxy based on electrical and data-center infrastructure exposure; add primary fiscal filings in next pass.",
    thesis: "Broad electrical and cooling exposure makes Schneider an important AI infrastructure supplier.",
    audit: "Needs official data-center order mix and cooling/electrical split.",
    valuationLens: "Diversified way to own power distribution and data-center electrical demand.",
  },
  {
    id: "vrt",
    name: "Vertiv",
    ticker: "VRT",
    layerId: "cooling",
    category: "physical infra",
    layerShare: 30,
    aiRevenueMix: 65,
    aiOpIncomeMix: 70,
    coverageAt15Gw: 55,
    substitutionRisk: "low",
    confidence: "proxy",
    sourceIds: [],
    sourceNote: "Proxy: Vertiv is highly exposed to data-center power/cooling, but this pass did not anchor a primary 2025 source.",
    thesis: "The cleanest public cooling/power systems beta in the map, especially for high-density AI racks.",
    audit: "Replace proxy with official backlog/orders and data-center revenue mix.",
    valuationLens: "High AI beta but already widely recognized by the market.",
  },
  {
    id: "mod",
    name: "Modine",
    ticker: "MOD",
    layerId: "cooling",
    category: "physical infra",
    layerShare: 12,
    aiRevenueMix: 32,
    aiOpIncomeMix: 36,
    coverageAt15Gw: 35,
    substitutionRisk: "medium",
    confidence: "proxy",
    sourceIds: [],
    sourceNote: "Proxy: thermal management exposure to data centers; primary-source audit still needed.",
    thesis: "Smaller cooling supplier with potentially higher incremental beta but lower certainty.",
    audit: "Needs segment revenue bridge and data-center backlog.",
    valuationLens: "More idiosyncratic than Vertiv; more sensitive to execution and customer concentration.",
  },
  {
    id: "asml",
    name: "ASML",
    ticker: "ASML",
    layerId: "lithography",
    category: "silicon",
    layerShare: 78,
    aiRevenueMix: 40,
    aiOpIncomeMix: 42,
    coverageAt15Gw: 95,
    substitutionRisk: "low",
    confidence: "derived",
    sourceIds: ["asml-2025", "asml-q425"],
    sourceNote: "ASML disclosed 2025 sales, backlog, EUV units and EUV bookings; AI exposure is derived from leading-edge semiconductor demand.",
    thesis: "The essential tool choke point for leading-edge AI silicon, but revenue is diversified across logic and memory cycles.",
    audit: "AI mix is intentionally below reference-style pure-play numbers because ASML does not sell only into AI.",
    valuationLens: "Durable monopoly-like position, but AI beta is diluted by customer capex cycles.",
  },
  {
    id: "amat",
    name: "Applied Materials",
    ticker: "AMAT",
    layerId: "lithography",
    category: "silicon",
    layerShare: 22,
    aiRevenueMix: 32,
    aiOpIncomeMix: 35,
    coverageAt15Gw: 75,
    substitutionRisk: "medium",
    confidence: "proxy",
    sourceIds: [],
    sourceNote: "Proxy: broad wafer fab equipment exposure; primary-source segment audit still needed.",
    thesis: "Broad equipment exposure to leading-edge logic, memory, and packaging rather than a single chokepoint.",
    audit: "Add official segment and end-market disclosures.",
    valuationLens: "AI helps WFE intensity, but multiple end markets drive the cycle.",
  },
  {
    id: "tsmc",
    name: "TSMC",
    ticker: "TSM",
    layerId: "foundry",
    category: "silicon",
    layerShare: 70,
    aiRevenueMix: 48,
    aiOpIncomeMix: 55,
    coverageAt15Gw: 82,
    substitutionRisk: "low",
    confidence: "derived",
    sourceIds: ["tsmc-2025"],
    sourceNote: "TSMC disclosed robust AI-related demand, advanced-node share, 3nm share, and advanced technologies at 74% of wafer revenue.",
    thesis: "The central foundry bottleneck for AI accelerators, but AI is mixed with smartphone, HPC and other advanced-node demand.",
    audit: "AI revenue mix is derived from HPC/advanced-node indicators, not directly reported.",
    valuationLens: "Best-in-class manufacturing moat with geopolitics and capex intensity as key risks.",
  },
  {
    id: "skhynix",
    name: "SK hynix",
    layerId: "memory",
    category: "silicon",
    layerShare: 50,
    aiRevenueMix: 55,
    aiOpIncomeMix: 80,
    coverageAt15Gw: 45,
    substitutionRisk: "low",
    confidence: "derived",
    sourceIds: ["skhynix-fy25"],
    sourceNote: "SK hynix attributed record 2025 results to AI memory competitiveness and HBM/high-value products.",
    thesis: "HBM leadership makes SK hynix one of the strongest memory-side AI beta names.",
    audit: "Revenue mix is derived from HBM/AI commentary, not a reported AI revenue percentage.",
    valuationLens: "High AI beta, but memory remains cyclical and supply additions matter.",
  },
  {
    id: "mu",
    name: "Micron",
    ticker: "MU",
    layerId: "memory",
    category: "silicon",
    layerShare: 22,
    aiRevenueMix: 35,
    aiOpIncomeMix: 50,
    coverageAt15Gw: 30,
    substitutionRisk: "low",
    confidence: "derived",
    sourceIds: ["micron-q225"],
    sourceNote: "Micron disclosed HBM revenue crossing $1B in fiscal Q2 2025 and record data-center DRAM revenue.",
    thesis: "Cleaner than commodity DRAM when HBM ramps, but still behind the leading HBM supplier.",
    audit: "Needs latest FY2025 full-year HBM and data-center revenue bridge.",
    valuationLens: "A high-cyclical-beta way to own memory tightness.",
  },
  {
    id: "tsmc-cowos",
    name: "TSMC CoWoS",
    ticker: "TSM",
    layerId: "packaging",
    category: "silicon",
    layerShare: 70,
    aiRevenueMix: 18,
    aiOpIncomeMix: 25,
    coverageAt15Gw: 50,
    substitutionRisk: "low",
    confidence: "proxy",
    sourceIds: ["tsmc-2025"],
    sourceNote: "Proxy: TSMC disclosed continued investment in advanced packaging; CoWoS revenue is not isolated.",
    thesis: "Advanced packaging remains a real accelerator bottleneck even if TSMC's total revenue mix dilutes it.",
    audit: "Needs CoWoS capacity and revenue estimates from primary or well-sourced secondary work.",
    valuationLens: "Packaging scarcity improves foundry pricing power but is only one component of TSMC.",
  },
  {
    id: "amkr",
    name: "Amkor",
    ticker: "AMKR",
    layerId: "packaging",
    category: "silicon",
    layerShare: 12,
    aiRevenueMix: 12,
    aiOpIncomeMix: 14,
    coverageAt15Gw: 35,
    substitutionRisk: "medium",
    confidence: "proxy",
    sourceIds: [],
    sourceNote: "Proxy: advanced packaging exposure, but no audited AI revenue bridge yet.",
    thesis: "Potential packaging beneficiary, but less directly tied to frontier accelerator bottlenecks than TSMC CoWoS.",
    audit: "Add official advanced packaging revenue and customer concentration.",
    valuationLens: "Lower AI beta, lower valuation intensity.",
  },
  {
    id: "nvda",
    name: "NVIDIA",
    ticker: "NVDA",
    layerId: "accelerators",
    category: "silicon",
    layerShare: 80,
    aiRevenueMix: 90,
    aiOpIncomeMix: 92,
    coverageAt15Gw: 75,
    substitutionRisk: "medium",
    confidence: "reported",
    sourceIds: ["nvda-fy26"],
    sourceNote: "FY26 Data Center revenue was $193.7B on $215.9B total revenue, so revenue AI/data-center mix is directly derived.",
    thesis: "The dominant accelerator and systems vendor; the clearest AI revenue beta in public markets.",
    audit: "Data-center is not perfectly equal to AI, but it is the best reported proxy.",
    valuationLens: "Highest quality and highest expectations; risk is priced-in status, not demand proof.",
  },
  {
    id: "amd",
    name: "AMD",
    ticker: "AMD",
    layerId: "accelerators",
    category: "silicon",
    layerShare: 8,
    aiRevenueMix: 48,
    aiOpIncomeMix: 45,
    coverageAt15Gw: 35,
    substitutionRisk: "medium",
    confidence: "derived",
    sourceIds: ["amd-fy25"],
    sourceNote: "FY2025 Data Center revenue was $16.6B on $34.6B total revenue; not all data-center revenue is AI accelerator revenue.",
    thesis: "AI accelerator upside exists, but EPYC CPUs are a major part of the data-center segment.",
    audit: "Needs Instinct-specific revenue disclosure to raise confidence.",
    valuationLens: "More upside to share gains, more uncertainty than NVIDIA.",
  },
  {
    id: "avgo",
    name: "Broadcom",
    ticker: "AVGO",
    layerId: "accelerators",
    category: "silicon",
    layerShare: 7,
    aiRevenueMix: 32,
    aiOpIncomeMix: 38,
    coverageAt15Gw: 85,
    substitutionRisk: "low",
    confidence: "derived",
    sourceIds: ["broadcom-fy25"],
    sourceNote: "Broadcom disclosed Q4 AI semiconductor revenue growth and Q1 FY26 AI semiconductor revenue guide of $8.2B.",
    thesis: "The strongest custom ASIC and Ethernet AI networking public proxy.",
    audit: "Annual AI mix is estimated from quarterly AI semiconductor run-rate against total revenue.",
    valuationLens: "More customer-specific and contract-driven than NVIDIA, with strong EBITDA support from software.",
  },
  {
    id: "mrvl",
    name: "Marvell",
    ticker: "MRVL",
    layerId: "accelerators",
    category: "silicon",
    layerShare: 5,
    aiRevenueMix: 35,
    aiOpIncomeMix: 38,
    coverageAt15Gw: 55,
    substitutionRisk: "medium",
    confidence: "proxy",
    sourceIds: [],
    sourceNote: "Proxy: custom silicon and data-center exposure; primary-source audit still needed.",
    thesis: "AI custom silicon and connectivity exposure, but disclosure is less clean in this pass.",
    audit: "Add fiscal-year data-center segment revenue and custom AI pipeline disclosures.",
    valuationLens: "Can benefit if ASIC demand broadens beyond the largest hyperscalers.",
  },
  {
    id: "anet",
    name: "Arista",
    ticker: "ANET",
    layerId: "optics",
    category: "silicon",
    layerShare: 22,
    aiRevenueMix: 45,
    aiOpIncomeMix: 50,
    coverageAt15Gw: 60,
    substitutionRisk: "medium",
    confidence: "derived",
    sourceIds: ["arista-fy25"],
    sourceNote: "Arista disclosed FY2025 revenue of $9B and said it exceeded AI networking goals.",
    thesis: "A prime Ethernet AI networking beneficiary, but cloud customer concentration matters.",
    audit: "Needs explicit AI networking revenue split if disclosed in presentations/calls.",
    valuationLens: "High-margin networking compounder exposed to AI cluster architecture choices.",
  },
  {
    id: "fn",
    name: "Fabrinet",
    ticker: "FN",
    layerId: "optics",
    category: "silicon",
    layerShare: 15,
    aiRevenueMix: 45,
    aiOpIncomeMix: 48,
    coverageAt15Gw: 50,
    substitutionRisk: "low",
    confidence: "proxy",
    sourceIds: ["fabrinet-fy25"],
    sourceNote: "Fabrinet disclosed record FY2025 revenue and strong demand, but AI/datacom mix needs a presentation-level bridge.",
    thesis: "Manufacturing leverage to optical modules and data-center interconnect demand.",
    audit: "Needs datacom/HPC revenue split from investor presentation.",
    valuationLens: "Cleaner optics manufacturing exposure, but customer and program concentration matter.",
  },
  {
    id: "cohr",
    name: "Coherent",
    ticker: "COHR",
    layerId: "optics",
    category: "silicon",
    layerShare: 18,
    aiRevenueMix: 38,
    aiOpIncomeMix: 42,
    coverageAt15Gw: 45,
    substitutionRisk: "medium",
    confidence: "proxy",
    sourceIds: [],
    sourceNote: "Proxy: optical networking exposure; primary-source audit still needed.",
    thesis: "Optical demand rises with AI clusters, but portfolio and balance-sheet complexity dilute the read.",
    audit: "Add networking/datacom revenue and AI customer commentary.",
    valuationLens: "More turnaround/portfolio risk than the pure-play optics names.",
  },
  {
    id: "smci",
    name: "Super Micro",
    ticker: "SMCI",
    layerId: "systems",
    category: "physical infra",
    layerShare: 18,
    aiRevenueMix: 65,
    aiOpIncomeMix: 60,
    coverageAt15Gw: 75,
    substitutionRisk: "high",
    confidence: "proxy",
    sourceIds: [],
    sourceNote: "Proxy: high AI server exposure, but not audited in this pass.",
    thesis: "High beta to AI rack demand, offset by fierce competition and execution/accounting risk.",
    audit: "Needs latest filings, AI server revenue mix, and margin bridge.",
    valuationLens: "High upside/high idiosyncratic risk.",
  },
  {
    id: "dell",
    name: "Dell",
    ticker: "DELL",
    layerId: "systems",
    category: "physical infra",
    layerShare: 22,
    aiRevenueMix: 20,
    aiOpIncomeMix: 18,
    coverageAt15Gw: 55,
    substitutionRisk: "medium",
    confidence: "proxy",
    sourceIds: [],
    sourceNote: "Proxy: AI server backlog and infrastructure solutions exposure; primary-source audit needed.",
    thesis: "Scale supplier of enterprise and AI servers, but corporate mix is diversified.",
    audit: "Add AI server backlog and ISG revenue bridge.",
    valuationLens: "Lower pure-play AI beta, potentially better valuation discipline.",
  },
  {
    id: "jbl",
    name: "Jabil",
    ticker: "JBL",
    layerId: "systems",
    category: "physical infra",
    layerShare: 12,
    aiRevenueMix: 26,
    aiOpIncomeMix: 28,
    coverageAt15Gw: 60,
    substitutionRisk: "medium",
    confidence: "proxy",
    sourceIds: [],
    sourceNote: "Proxy: EMS/rack integration exposure; source audit still pending.",
    thesis: "Manufacturing and integration leverage to AI systems, but margin capture can be limited.",
    audit: "Add disclosed AI revenue or cloud infrastructure segment detail.",
    valuationLens: "Picks-and-shovels exposure with lower gross margin power.",
  },
  {
    id: "msft",
    name: "Microsoft / Azure",
    ticker: "MSFT",
    layerId: "hyperscalers",
    category: "cloud",
    layerShare: 26,
    aiRevenueMix: 14,
    aiOpIncomeMix: 16,
    coverageAt15Gw: 110,
    substitutionRisk: "low",
    confidence: "reported",
    sourceIds: ["microsoft-q3fy26", "microsoft-cloud-q3fy26"],
    sourceNote: "Microsoft disclosed AI business annual revenue run rate over $37B and Azure growth of 40%.",
    thesis: "The strongest enterprise distribution layer for AI infrastructure and copilots.",
    audit: "AI run-rate divided by total company revenue understates cloud-specific AI beta but avoids overclaiming.",
    valuationLens: "High-quality AI monetization, but capex intensity pressures cloud gross margin.",
  },
  {
    id: "aws",
    name: "Amazon AWS",
    ticker: "AMZN",
    layerId: "hyperscalers",
    category: "cloud",
    layerShare: 30,
    aiRevenueMix: 9,
    aiOpIncomeMix: 15,
    coverageAt15Gw: 105,
    substitutionRisk: "low",
    confidence: "reported",
    sourceIds: ["amazon-q126"],
    sourceNote: "Amazon disclosed AWS AI revenue run-rate above $15B and rapid Bedrock usage growth.",
    thesis: "Massive cloud distribution with custom silicon optionality; AI is large but diluted by total Amazon scale.",
    audit: "Use AWS segment revenue rather than total Amazon revenue for a cloud-only view in the next pass.",
    valuationLens: "AI monetization has to outrun capex and depreciation pressure.",
  },
  {
    id: "orcl",
    name: "Oracle OCI",
    ticker: "ORCL",
    layerId: "hyperscalers",
    category: "cloud",
    layerShare: 8,
    aiRevenueMix: 55,
    aiOpIncomeMix: 45,
    coverageAt15Gw: 130,
    substitutionRisk: "medium",
    confidence: "derived",
    sourceIds: ["oracle-q3fy26"],
    sourceNote: "Oracle disclosed $553B RPO, most Q3 increase related to large-scale AI contracts, often prepaid or customer-GPU funded.",
    thesis: "The most dramatic AI backlog story among diversified clouds, but counterparty concentration is the question.",
    audit: "Revenue mix is derived from RPO commentary, not recognized revenue.",
    valuationLens: "Backlog quality and funding structure matter more than headline RPO.",
  },
  {
    id: "crwv",
    name: "CoreWeave",
    ticker: "CRWV",
    layerId: "neoclouds",
    category: "cloud",
    layerShare: 45,
    aiRevenueMix: 100,
    aiOpIncomeMix: 95,
    coverageAt15Gw: 21,
    capacityGw: 3.1,
    substitutionRisk: "high",
    confidence: "reported",
    sourceIds: ["coreweave-q425", "coreweave-q225"],
    sourceNote: "CoreWeave disclosed $66.8B revenue backlog, >850 MW active power, and about 3.1 GW contracted power at FY2025 year-end.",
    thesis: "Pure-play GPU cloud exposure with real contracted power, but customer concentration and financing risk are central.",
    audit: "Coverage directly uses contracted power divided by the scenario GW assumption.",
    valuationLens: "The cleanest neocloud beta, with the most balance-sheet sensitivity.",
  },
  {
    id: "nbis",
    name: "Nebius",
    ticker: "NBIS",
    layerId: "neoclouds",
    category: "cloud",
    layerShare: 20,
    aiRevenueMix: 100,
    aiOpIncomeMix: 65,
    coverageAt15Gw: 12,
    substitutionRisk: "high",
    confidence: "speculative",
    sourceIds: [],
    sourceNote: "Placeholder proxy pending independent source audit.",
    thesis: "Potential AI cloud pure play, but this pass does not yet have enough primary-source support.",
    audit: "Needs contracted power, backlog, customer concentration, and funding details.",
    valuationLens: "Speculative until sourced.",
  },
  {
    id: "snow",
    name: "Snowflake",
    ticker: "SNOW",
    layerId: "apps",
    category: "apps",
    layerShare: 24,
    aiRevenueMix: 18,
    aiOpIncomeMix: 20,
    coverageAt15Gw: 0,
    substitutionRisk: "medium",
    confidence: "derived",
    sourceIds: ["snowflake-fy26"],
    sourceNote: "Snowflake disclosed 9,100+ accounts using AI features and 2,500 Snowflake Intelligence accounts in three months.",
    thesis: "Application/data layer capture depends on AI workloads expanding data consumption and governed enterprise usage.",
    audit: "Not included in the 15 physical supply-chain layers; shown in the public-equity lens.",
    valuationLens: "AI can improve growth durability, but consumption optimization remains the counterweight.",
  },
  {
    id: "now",
    name: "ServiceNow",
    ticker: "NOW",
    layerId: "apps",
    category: "apps",
    layerShare: 24,
    aiRevenueMix: 20,
    aiOpIncomeMix: 24,
    coverageAt15Gw: 0,
    substitutionRisk: "low",
    confidence: "derived",
    sourceIds: ["servicenow-q126"],
    sourceNote: "ServiceNow disclosed Q1 2026 subscription revenue growth and Now Assist customers over $1M ACV growing over 130% YoY.",
    thesis: "Workflow control point for enterprise AI, with less physical capex risk than infrastructure names.",
    audit: "Needs Now Assist ACV contribution, not just customer growth.",
    valuationLens: "High-quality application-layer AI monetization candidate.",
  },
];

export const methodology = [
  {
    title: "AI revenue mix",
    body: "Reported when a company discloses AI or data-center revenue. Derived when a disclosed segment is the best proxy. Proxy/speculative when AI is embedded in broader end markets.",
  },
  {
    title: "Layer share",
    body: "A directional share of the investable public-company layer, not a precise industry market share. For fragmented layers, this is intentionally low confidence.",
  },
  {
    title: "Coverage",
    body: "A 15GW scenario screen. For power/neocloud names with contracted GW, coverage is capacity divided by the selected demand scenario. For other bottlenecks, it is an order/backlog proxy.",
  },
  {
    title: "Substitution risk",
    body: "Qualitative risk that the investor picked the wrong company inside the right layer. Low means few credible substitutes or high switching cost; high means crowded or execution-sensitive.",
  },
];

export function coverageCompanies(demandGw: number) {
  return companies.map((company) => ({
    ...company,
    coverage: company.capacityGw ? (company.capacityGw / demandGw) * 100 : company.coverageAt15Gw * (15 / demandGw),
  }));
}
